trackpy.api.SubnetOversizeException
===================================

.. currentmodule:: trackpy.api

.. autoexception:: SubnetOversizeException